### ISSUE TITLE
How to process the dataset?

### ISSUE THREAD

**Issue by Git-oNmE** [ispc-lab/HRegNet#9]
I run the command `sh scripts/train_kitti_det.sh`, and I got the error message like this:
```
Traceback (most recent call last):
  File "/media/data3/hlf_data/HRegNet0/HRegNet/train_feats.py", line 243, in <module>
    train_feats(args)
  File "/media/data3/hlf_data/HRegNet0/HRegNet/train_feats.py", line 159, in train_feats
    for i, data in pbar:
  File "/home/hlf/miniconda3/envs/HRegNet/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/hlf/miniconda3/envs/HRegNet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/hlf/miniconda3/envs/HRegNet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/hlf/miniconda3/envs/HRegNet/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/hlf/miniconda3/envs/HRegNet/lib/python3.9/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hlf/miniconda3/envs/HRegNet/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hlf/miniconda3/envs/HRegNet/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hlf/miniconda3/envs/HRegNet/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/data3/hlf_data/HRegNet0/HRegNet/data/kitti_data.py", line 89, in __getitem__
    src_points = read_kitti_bin_voxel(data_dict['points1'], self.npoints, self.voxel_size)
  File "/media/data3/hlf_data/HRegNet0/HRegNet/data/kitti_data.py", line 20, in read_kitti_bin_voxel
    scan = np.fromfile(filename, dtype=np.float32, count=-1).reshape([-1,4])
FileNotFoundError: [Errno 2] No such file or directory: '/media/data3/hlf_data/HRegNet0/HRegNet/data/kitti_list/01/velodyne/000204.bin'
```
Seems like I didn't process the data files rightly.

I see it in the readme.md that the files should be organized like this: 
![image](https://user-images.githubusercontent.com/29742421/168416319-bcddd7d2-7624-4579-bd6a-7ace0bc7cf49.png)

But I don't know how to come to this. Mine is just like thiis:
![image](https://user-images.githubusercontent.com/29742421/168416383-6f042cca-3de2-4836-a323-1c0642e518d3.png)

Someone help me please? Thanks!

**Comment by FanLu97** [comment]
The lists of each dataset in this repo only provide refined ground truth transformations. You need to download the original dataset. The website is listed below:
KITTI: http://www.cvlibs.net/datasets/kitti/eval_odometry.php
NuScenes: https://www.nuscenes.org/nuscenes#download
After downloading, you should organize the dataset as described in the README.

**Comment by Git-oNmE** [comment]
> The lists of each dataset in this repo only provide refined ground truth transformations. You need to download the original dataset. The website is listed below: KITTI: http://www.cvlibs.net/datasets/kitti/eval_odometry.php NuScenes: https://www.nuscenes.org/nuscenes#download After downloading, you should organize the dataset as described in the README.

![image](https://user-images.githubusercontent.com/29742421/168420793-f6112711-5bda-49b5-b727-ccea37b2e0d7.png)

I went to the website and see several download links, could you tell me which items to download please? Thanks :)

**Comment by FanLu97** [comment]
You should download the velodyne laser data, calibration files and ground truth poses.

**Comment by Git-oNmE** [comment]
> You should download the velodyne laser data, calibration files and ground truth poses.

Thanks for your timely and useful reply!
